### ISSUE TITLE
STEP1. サーバーが立ち上がるようにしよう！

### ISSUE THREAD

**Issue by yukiwakisaka** [RyoheiYamamoto/simple-java-http-server#2]
サーバーが立ち上がる = サーバーソケットに指定したホストとポートを割り当て、接続を待ち受ける状態。
- [x] `STEP1`ブランチを作成する
- [x] Javaでサーバーソケットを作成する方法を調べる
- [x] 作成したサーバーソケットにホストとポートを割り当てる（= バインドする）方法を調べる
- [x] サーバーソケットを作成し、ホストとポートを割り当てるところまでコードを書いてみる
- [x] 割り当てができたら、コンソールに`serving HTTP on localhost port 8000 ...`と出力されるようにする
- [x] サーバーソケットがリクエストを待機するようコードを書いてみる
- [x] リクエストが来たら、コンソールに`Hello Request!`と出力されるようにする
- [ ] push & commitし、Pull Requestを作る
- [ ] PRビルドが通ることを確認し、Assigneesにレビュワーを指定してレビューを依頼する

**Comment by RyoheiYamamoto** [comment]
しゅうりょう

**Comment by yukiwakisaka** [comment]
## チェック項目

### 起動
ログ: Serving HTTP on localhost port 8000 ...

### localhost:8000 にアクセス
ブラウザ: 反応なし
ログ: Hello Request!
（1アクセスごとに、アプリが終了する状態でOK）
