### ISSUE TITLE
STEP2. 「Hello Client!」と返ってくるようにしよう！

### ISSUE THREAD

**Issue by yukiwakisaka** [RyoheiYamamoto/simple-java-http-server#3]
- [ ] ``STEP2``ブランチを作成する
- [ ] ServerSocket#accept()メソッドが返すのはSocketオブジェクト。java.netパッケージおよびSocketクラスのJavadocを熟読し、クライアントにデータを返す方法を検討する
- [ ] Hello Client!という文字列をバイト列に変換する方法を調べる
- [ ] クライアントに「Hello Client!」と返すようにコードを書いてみる
- [ ] サーバーを起動して、動作を確認する
- [ ] ブラウザでリロードをしても「Hello Client!」と表示されるようにコードを修正する
- [ ] push & commitし、Pull Requestを作る
- [ ] PRビルドが通ることを確認し、Assigneesにレビュワーを指定してレビューを依頼する

**Comment by RyoheiYamamoto** [comment]
おk

**Comment by yukiwakisaka** [comment]
## チェック項目

### localhost:8000 にアクセス
ブラウザ: Hello Client! の文字列が表示される
1アクセスごとに、アプリが終了しない（連続してアクセスができる）
